# config_segmentation_finetune.yaml

experiment:
  name: "segmentation_finetune_gdice"
  
training:
  epochs: 100
  batch_size: 2
  learning_rate: 0.0001
  
data:
  preprocessed_dir: "/home/pahm409/preprocessed_stroke_foundation"
  splits_file: "splits_stratified.json"
  datasets:
    - "ATLAS"
    - "UOA_Private"
